### PR TITLE
remove project name validation

### LINKED ISSUE #208: remove the project name validation
We're getting the project name implicitly from the cwd. 

https://github.com/google/stagehand/blob/master/lib/src/cli_app.dart#L161

We still want to keep the project name normalization.

### PR DESCRIPTION
**Pull request by devoncarew**
Fix #208, @pq.

### CODE REVIEW

**Comment by pq** [comment]
LGTM!

**Comment by alexander-doroshko** [comment]
Should normalizeProjectName() now take care of the first character to match [A-Za-z]?

**Comment by alexander-doroshko** [comment]
@devoncarew @pq Looks like normalizeProjectName() now should take care of the first character to match [A-Za-z]. May be some more normalization needed, for example I'm not sure if Chinese or Russian symbols in the project name will work. And special symbols like `~!@#$%^&*()_+='"\|/<>[]{}

**Comment by devoncarew** [comment]
@alexander-doroshko, agreed! We should do a bit more rigorous normalization. Is this something you'd be interested in contributing? Otherwise I can open a separate issue for it.

**Comment by alexander-doroshko** [comment]
@devoncarew Yes, I can do it myself if you want. Just to make sure: are restrictions for the project name the same as for Dart lang identifier?

**Comment by devoncarew** [comment]
Yup, here are the conventions: https://www.dartlang.org/tools/pub/pubspec.html#name

Some of them are more important than others. I'm not exactly sure what to do if the directory name starts with numbers, or invalid chars. Do we just remove chars until we get to a legal one? Or convert them to more legal chars? Or prefix with a legal char? None of those options are particularly appealing.

**Pull request merged**
