### PR TITLE
move todo component under lib/src

### PR DESCRIPTION
**Pull request by jakemac53**
This follows new recommendations based on dartdevc and how it auto-creates modules based on "public" files.

Note that the main project works fine with dartdevc, but the tests seem to fail with a runtime type check. I am looking into that now and will file a bug or pull request on the angular test repo.

### CODE REVIEW

**Comment by kwalrath** [comment]
LGTM. I'm going to take a look at which docs and examples should change to match this.

**Comment by jakemac53** [comment]
Fyi somebody else will have to merge I don't have access to this repo. All ready as far as I am concerned though.

**Comment by chalin** [comment]
I would tend to agree.

On the other hand, it's been a convention (at least on the TS side), to put the collection of files related to one component under a folder with the same name as the component.

**Comment by kwalrath** [comment]
@jakemac53 could you please resolve the conflicts?

**Comment by kwalrath** [comment]
I'm going to create a PR with these changes.

**Comment by jakemac53** [comment]
@kwalrath updated

**Pull request merged**
