### PR TITLE
rename and update the shelf template

### PR DESCRIPTION
**Pull request by devoncarew**
@kevmoo, update the version for the shelf template. Also, change the id to match the new {type}-{subtype} scheme.

### CODE REVIEW

**Comment by kevmoo** [comment]
LGTM!

**Comment by kevmoo** [comment]
Yes – I'm trying to encourage more direct pushing instead of merging. Clean history FTW!

**Comment by devoncarew** [comment]
:)

Once github gets a button for that in their PR UI, I'll push it.

**Comment by kevmoo** [comment]
```
[alias]
  pr = "!f() { git fetch origin refs/pull/$1/head:pr/$1; } ; f"
  pr-upstream = "!f() { git fetch upstream refs/pull/$1/head:pr/$1; } ; f"
```

Add this to `$HOME/.gitconfig` – makes it easy to deal w/ pull requests locally.

**Pull request merged**
