### PR TITLE
Add a component CSS file to the Angular template

### PR DESCRIPTION
**Pull request by filiph**
As proposed in issue https://github.com/google/stagehand/issues/332

### CODE REVIEW

**Comment by kwalrath** [comment]
LGTM, though I should test this. We should also update CHANGELOG.md.

**Comment by kwalrath** [comment]
On second thought... This has implications for the angular.io samples. @chalin might have an opinion.

**Comment by filiph** [comment]
I just want to add that this change should make the tutorials easier and less error-prone. 

The step of creating a .css file and then adding its path to the component's metadata always felt like a chore to me.

**Comment by chalin** [comment]
I agree about the inclusion of the style file, but see https://github.com/google/stagehand/issues/332#issuecomment-242222749 for a suggested alternative to `:host`.

**Comment by kwalrath** [comment]
@filiph what do you have to say about `:host`?

**Comment by kwalrath** [comment]
Merging, per discussion at #332.

**Pull request merged**
