### PR TITLE
Add webcomponents-lite.min.js to web/index.html

### PR DESCRIPTION
**Pull request by ntaoo**
We still need the polyfill for Firefox, Safari, IE, and Edge.

### CODE REVIEW

**Comment by devoncarew** [comment]
@jakemac53, can you review?

**Comment by jakemac53** [comment]
Lgtm

**Comment by devoncarew** [comment]
@ntaoo, can you add yourself to the authors (https://github.com/google/stagehand/blob/master/AUTHORS) file as part of this PR? Thanks!

**Comment by ntaoo** [comment]
Okey, is this format alright?

**Comment by devoncarew** [comment]
Thanks!

**Pull request merged**
