### PR TITLE
Added <base href="/"> to index.html in angular templates (#360)

### PR DESCRIPTION
**Pull request by switchspan**
Hi! Saw this in issues and figured it was a quick fix. I was 'bitten' by the absence of this tag on the tour of heroes tutorial's routing section: https://webdev.dartlang.org/angular/tutorial/toh-pt5 (don't worry -- I recovered without a scar)

### CODE REVIEW

**Comment by kwalrath** [comment]
@chalin what do you say?

**Comment by chalin** [comment]
@switchspan, thanks for the update.

@kwalrath - I think that I'd like to see the following right after the `<base href>` element:
```
    <!-- For testing in WebStorm use: -->
    <!-- base href="/dart/web/" -->
```
We had this comment we have in the toh-5 `index.html`. WDYT?  If Kathy agrees, can you make that update @switchspan?

**Comment by switchspan** [comment]
@chalin No prob -- I can update it. @kwalrath what say you?

**Comment by kwalrath** [comment]
Sounds good to me. Thanks, @switchspan & @chalin!

**Comment by switchspan** [comment]
@kwalrath @chalin No problem. I added the comments and re-ran a build from grind (almost forgot this :-o ). It should be good to go now.

**Comment by kwalrath** [comment]
My only question... Should we really be adding 3 lines to web-angular-quickstart? Since it doesn't do any routing and this is supposed to be the minimum possible app, maybe this should be handled in toh-5 directly?

**Comment by switchspan** [comment]
@kwalrath Good point. I can definitely see an argument for adding it to toh-5 so that others following it are aware that when using routing the base tag must be present, or APP_BASE_HREF needs to be imported & provided.

Should I remove it from quickstart and we punt that part over to whatever repo has the toh-5 content?

**Comment by kwalrath** [comment]
Yes, let's do that. Thanks VERY much for your responsiveness!

While you're in there, could you update the CHANGELOG and put the
#unreleased item under 1.0.21? (You did the right thing, they technically
didn't. :) I plan to release 1.0.21 as soon as your change is in.

**Comment by switchspan** [comment]
@kwalrath No problem. I can do that. Also -- can you point me to the right repo to submit an update for the toh-5 docs?

**Comment by kwalrath** [comment]
toh-5 docs & examples are all in https://github.com/dart-lang/site-webdev.

The webdev build system is a bit gnarly, so if it gets too onerous, just tell me what to change and I'll make it happen. Thank you!

**Comment by switchspan** [comment]
@kwalrath Thanks -- Will do! The lastest changes are now commited to the pr branch.

**Comment by chalin** [comment]
Hey all. I'm in the middle of something. Could we just put a hold on this for a little while. I'll need to discuss some broader issues with @kwalrath offline. Thanks.

**Comment by switchspan** [comment]
@chalin Sure. I will hold up on any submissions of code/issues to site-webdev til I hear from you.

**Comment by kwalrath** [comment]
Patrice and I have talked, and we're going to keep base href in web-angular-quickstart. But I'm going to make that change myself, since I'm going to change the name of that template anyway.

I believe Patrice is midway through his router changes, so hold off on those...

Thanks very much for your PR!

**Comment by kwalrath** [comment]
Actually, since base href makes the initial WebStorm experience bad, I'm rethinking how we'll handle it.

**Comment by switchspan** [comment]
@kwalrath I just ran it under WebStorm and I can see what you are talking about. :-(
One path might be removing it from the quickstart and adding routing to the regular angular template -- but that might be overkill if we don't need routing right away. I will take a look and see what yeoman is creating template-wise for a full angular 2 project.

**Comment by kwalrath** [comment]
We're thinking about adding something like this just after the `<head>` tag:

```
    <!-- Set the base href dynamically so that routing works with most servers.
         Don't do this in production!
         Details: webdev.dartlang.org/angular/guide/router -->
    <script>document.write('<base href="' + document.location + '"/>');</script>
```

**Comment by kwalrath** [comment]
See #365 for related changes.

**Pull request merged**
