### PR TITLE
improve the css for web-simple; add favicons

### PR DESCRIPTION
**Pull request by devoncarew**
- improve the css for the `web-simple` template so its a bit more visually appealing
- add a favicon for web-simple - avoid a 404 for the sample out of the box
- add a favicon for web-angular (fix https://github.com/google/stagehand/issues/418)

### CODE REVIEW

**Comment by devoncarew** [comment]
@kwalrath

**Comment by kwalrath** [comment]
Btw, thanks very much for this PR!

**Comment by devoncarew** [comment]
Would you mind sending the bits? I think we can also scale the image down to 64x64 (the same as the dart favicon). Thanks!

**Comment by devoncarew** [comment]
(resized to 64x64)

**Comment by kwalrath** [comment]
I'll update the changelog to mention the favicons.

**Pull request merged**
