### PR TITLE
prep for a new release

### PR DESCRIPTION
**Pull request by devoncarew**
prep for a new release to capture the angular template:

- tweak the gitignore files
- rev to `0.2.5`

@kevmoo

### CODE REVIEW

**Comment by kevmoo** [comment]
While you're editing ignores, wanna remove `.project` and `.buildlog`? This were Dart Editor specific – nothing to do with pub

**Comment by devoncarew** [comment]
sgtm

**Comment by devoncarew** [comment]
published, and the web site was updated: http://stagehand.pub/

**Comment by kevmoo** [comment]
:metal:

**Pull request merged**
