### PR TITLE
Add an initial IntelliJ JavaScript Debug launch configuration for the AngularDart sample.

### PR DESCRIPTION
**Pull request by jwren**
@kwalrath  
@devoncarew

### CODE REVIEW

**Comment by kwalrath** [comment]
IntelliJ only, not WebStorm?

**Comment by jwren** [comment]
WebStorm as well.  I say IntelliJ, but I mean any JetBrains IDE.

**Comment by kwalrath** [comment]
The same problem occurs in IntelliJ 2017.1.

For either one, if I move the .idea directory elsewhere, I can open the project successfully. (I can then move it back, and the IDE will behave.)

**Comment by alexander-doroshko** [comment]
Please see my comment in https://github.com/google/stagehand/issues/389#issuecomment-294358780
I think stagehand shouldn't generate IDE-specific files for the following reasons:
- General consideration: such a tool should not be tied to any specific IDE. It's great when the toolchain (stagehand, VM, pub, etc.) allow playing with the technology using just a command line, without using the IDE at all. And at the moment it is the case.
- Run configuration is **already** created by the IDE right after passing new Dart project wizard and calling stagehand.  See [the code](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/projectWizard/DartProjectTemplate.java#L101). Are there any known bugs or usability issues with it? Let's fix them at the IDE end!
- IDE always knows how to create the best possible run configuration, depending on the IDE version or whatever else. Stagehand can't know it. Each IDE version is compatible with itself by definition.
- And one more show-stopper. Stagehand has no clue what URL to put into the generated run configuration. Why `http://localhost:8080`? No server is there with this port. IDE's default is `63342` and the correct URL is like `http://localhost:63342/project_name/web/index.html`. When opened - IDE starts Pub Serve on a random free port and redirects there, Pub's port is not known in advance. But even the `63342` port must not be hardcoded as there are use cases when users change it in the IDE settings. So Stagehand can't know the correct URL. But the IDE knows everything it needs.

**Comment by alexander-doroshko** [comment]
And one more stopper:
- IntelliJ IDEA allows having more than one Dart modules. In an existing project, you may click File -> New module and create one more Dart project from stagehand template as a new module of the same IntelliJ IDEA project. In this case new module content folder location and existing `.idea` folder location are not dependent, they may be completely in different places on the computer. Stagehand knows neither where to generate `.idea/runConfiguration/angular_dart.xml` file, nor whether it is going to introduce conflicts with existing RCs with the same name.

**Comment by alexander-doroshko** [comment]
And one more:
- IntelliJ IDEA Community Edition doesn't have JS Debugging support. Generating a run configuration there causes a confusing error message. Stagehand doesn't know whether the client supports JS debugger or not.

**Comment by kwalrath** [comment]
Closing due to issues raised by @alexander-doroshko.

**Pull request closed without merging**
