### PR TITLE
Update web-angular to latest

### PR DESCRIPTION
**Pull request by kevmoo**
CC @kwalrath

### CODE REVIEW

**Comment by kwalrath** [comment]
Thanks for the PR! I'm going to wait on publishing this until the angular.io site is updated.

@chalin

**Comment by kwalrath** [comment]
We also need to update lib/src/cli_app.dart before publishing...

**Comment by kwalrath** [comment]
angular.io/dart is updated, so I'll update stagehand now.

**Comment by kevmoo** [comment]
> We also need to update lib/src/cli_app.dart before publishing...

@kwalrath explain?

**Comment by kwalrath** [comment]
https://github.com/google/stagehand/wiki/Pushing-a-new-version

**Comment by kevmoo** [comment]
> https://github.com/google/stagehand/wiki/Pushing-a-new-version
😵

**Pull request merged**
