### PR TITLE
Update angular2 template to beta.3

### PR DESCRIPTION
**Pull request by andresaraujo**
Bumps version of Angular 2 template to beta 3

### CODE REVIEW

**Comment by kasperpeulen** [comment]
LGTM!

**Comment by kwalrath** [comment]
@andresaraujo could you please add yourself to stagehand/AUTHORS?

**Comment by andresaraujo** [comment]
Done @kwalrath

**Comment by kwalrath** [comment]
Looks good. Thanks, @andresaraujo!

**Pull request merged**
