### PR TITLE
update the analysis options file

### PR DESCRIPTION
**Pull request by devoncarew**
@kevmoo, @kwalrath, @chalin, update the analysis options excludes.

### CODE REVIEW

**Comment by kevmoo** [comment]
Oops...we chat to make sure this file matches the template versions – just for consistency.

Will need to tweak that...

**Comment by devoncarew** [comment]
Don't think this needs to match the template analysis options file - this is for use by the project itself (we want these excludes in order for the project to analyze cleanly).

**Comment by devoncarew** [comment]
Ah, this is copied into the template directories? I'll re-visit this PR.

**Comment by devoncarew** [comment]
Updated. The dev builds seem really unhappy - I don't believe related to this PR.

**Comment by devoncarew** [comment]
@kevmoo ptal - not clear what is causing the travis failures; I've restarted the bots

**Comment by kwalrath** [comment]
I've restarted the dev builds again, but I don't have high hopes. @kevmoo, are any other projects' dev release tests timing out?

**Comment by kevmoo** [comment]
@kwalrath @devoncarew there are known issues with Dartium and with API changes.

I haven't seen this issue in particular, though.

**Comment by chalin** [comment]
I restarted the Travis builds and all checks are passing now.

**Pull request merged**
